apiVersion: v1
entries:
  kvk:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-10-06T12:27:27.6829031Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 53d11e829efecff0802c02ada46146d895c7456697a457957760a9f303e43078
    home: kvk.zuid-drecht.nl
    icon: kvk.zuid-drecht.nl
    name: kvk
    urls:
    - kvk-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-06T12:27:27.6763943Z"
