apiVersion: v1
entries:
  kvk:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-09-01T10:33:20.4160728Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: bf49fd588ab98ee79361ea3c2d68c9fd41d0a0bddfbccf4ced67f6ba86d8bb73
    home: kvk.zuid-drecht.nl
    icon: kvk.zuid-drecht.nl
    name: kvk
    urls:
    - kvk-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-01T10:33:20.4071683Z"
